version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1 # Use the version you prefer
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false # Disable security for local testing (not recommended for production)
      - discovery.type=single-node # Run in single-node mode for local testing
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust JVM memory as needed
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1 # Match Elasticsearch version
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge